// Written by scripts/docs-content.mjs from README.md, LICENSE.md and docs/*.md.
// The deploy build rewrites this, so an edit to any of them ships either way. Run `mise run docs`
// to refresh the committed copy that local dev and the tests read.

export const README_MD = [
  "# pages",
  "",
  "A website you talk to Claude to build.",
  "",
  "Deploy it to your own Netlify account, connect Claude, and ask it to publish pages. Markdown gets a clean theme, HTML is served exactly as written.",
  "",
  "Lists of things (products, posts, events) can live in a data collection instead of being typed into a page. Claude edits one item at a time, the page fetches the whole collection as JSON, and nothing has to be rewritten to change a price.",
  "",
  "## Not a static site generator",
  "",
  "This deploys once and then stops being a build. One function serves every page, collection and",
  "asset out of storage, so publishing writes a record and the next visitor sees it. There is no",
  "rebuild, no deploy, and no build minutes burned when you change a word.",
  "",
  "Your content never enters this repository. A deploy happens when the site's *code* changes, which",
  "is when you take an upstream update. Writing a page is not a code change and does not need one.",
  "",
  "## Deploy",
  "",
  "[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/celsoft-com/pages)",
  "",
  "Open your site and pick an admin password. That's the whole setup.",
  "",
  "### Deploying from a fork",
  "",
  "The button copies this repo into your account with no link back, so later improvements never reach you. If you want them, fork the repo first and point Netlify at your fork instead (**Add new project → Import an existing project**).",
  "",
  "GitHub's **Sync fork** button then pulls in upstream changes, and Netlify redeploys on push. Still no checkout, no CLI.",
  "",
  "## Connect Claude",
  "",
  "Open **Connections** in your site, copy the URL, and add it as a custom connector in Claude. Sign in with your admin password and approve.",
  "",
  "Then ask Claude to publish a page.",
  "",
  "## Connect a script, a cron job, or an agent",
  "",
  "Anything without a browser talks to the site over its REST API instead. Open **Connections**,",
  "create an API token under **API tokens**, and pick whether it may write or only read.",
  "",
  "There is a skill that teaches any agent how to use it. Install it once:",
  "",
  "```",
  "npx skills add celsoft-com/pages --skill '*' -g -y",
  "```",
  "",
  "The flags matter: without them it opens an interactive picker. Add `-a '*'` if it asks which agent",
  "to install to.",
  "",
  "Then tell your agent your site's address and give it the token, and it will work out the rest",
  "from the site itself. It reaches Claude Code, Cursor, Codex and anything else that reads the",
  "[Agent Skills](https://github.com/anthropics/skills) format.",
  "",
  "Calling it directly is two lines:",
  "",
  "```",
  "curl -H \"Authorization: Bearer $TOKEN\" https://your-site.example/api/v1",
  "curl -H \"Authorization: Bearer $TOKEN\" -H 'content-type: application/json' \\",
  "  -d '{\"path\":\"/beers\",\"fields\":{\"name\":\"Pilsner\"}}' \\",
  "  https://your-site.example/api/v1/put_item",
  "```",
  "",
  "`GET /api/v1` lists every tool the token may call, with its JSON Schema. That list is generated",
  "from the site, so it is never out of date.",
  "",
  "It is plain HTTP and JSON, so any language talks to it with nothing installed:",
  "",
  "```python",
  "import json, urllib.request",
  "",
  "req = urllib.request.Request(",
  "    f\"{SITE}/api/v1/put_item\",",
  "    data=json.dumps({\"path\": \"/beers\", \"fields\": {\"name\": \"Pilsner\"}}).encode(),",
  "    headers={\"Authorization\": f\"Bearer {TOKEN}\", \"Content-Type\": \"application/json\"},",
  ")",
  "print(json.load(urllib.request.urlopen(req)))",
  "```",
  "",
  "## Documentation",
  "",
  "Every deploy serves its own reference at `/docs`: this README, the connector, the REST API, and",
  "every tool with its arguments and its reply. It is generated from the code that deploy is running,",
  "so it describes your site rather than a version of it somebody wrote down once.",
  "",
  "## License",
  "",
  "[MIT](LICENSE.md)",
  "",
].join("\n");

export const LICENSE_MD = [
  "# MIT License",
  "",
  "Copyright (c) 2026 Sean O'Dell",
  "",
  "Permission is hereby granted, free of charge, to any person obtaining a copy",
  "of this software and associated documentation files (the \"Software\"), to deal",
  "in the Software without restriction, including without limitation the rights",
  "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
  "copies of the Software, and to permit persons to whom the Software is",
  "furnished to do so, subject to the following conditions:",
  "",
  "The above copyright notice and this permission notice shall be included in all",
  "copies or substantial portions of the Software.",
  "",
  "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
  "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
  "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
  "SOFTWARE.",
  "",
].join("\n");

// Every file in docs/, carried verbatim. Frontmatter is parsed at runtime by topics.ts, so this
// stays a copy of what is on disk and nothing about a topic is decided here.
export const TOPIC_SOURCES: { slug: string; source: string }[] = [
  {
    slug: "api",
    source: [
    "---",
    "title: Connecting a client",
    "order: 20",
    "---",
    "",
    "# Connecting a client",
    "",
    "One API with two services in front of it. Both carry the same tools, take the same arguments and",
    "return the same results; what differs is how a client signs in, how a call is wrapped, and what",
    "comes back when one fails. Pick by what the client is: **MCP** for a chat client that can sign a",
    "person in, **REST** for a script, a cron job or an agent with no browser.",
    "",
    "Every call itself is documented once, both ways, in the [tool reference](/docs/tools).",
    "",
    "## Over MCP",
    "",
    "Connector URL: `{{mcp_url}}`",
    "",
    "Add it in Claude as a custom connector, sign in with the site's admin password and approve.",
    "",
    "Signing in is authorization code with PKCE and dynamic client registration, hand-rolled on this",
    "site, so a client discovers everything it needs from two well-known documents:",
    "",
    "```",
    "GET {{site_url}}/.well-known/oauth-authorization-server",
    "GET {{site_url}}/.well-known/oauth-protected-resource",
    "```",
    "",
    "A bearer token minted in the admin is accepted here too: the credential decides what a caller may",
    "do, not the door it came through.",
    "",
    "POST only, JSON-RPC 2.0, protocol version `{{protocol_version}}`. The methods are `initialize`,",
    "`ping`, `tools/list`, `tools/call`, and the `notifications/initialized` and",
    "`notifications/cancelled` notifications. A batch of messages in one array is answered with an array.",
    "",
    "A tool call comes back as text: the result rendered into a sentence for a reader. A tool that",
    "refuses answers with that same text and `isError: true`, so the JSON-RPC response is a success",
    "either way and there is no status code to read.",
    "",
    "## Over REST",
    "",
    "Base URL: `{{api_url}}`",
    "",
    "POST the arguments as a JSON object to the tool's own URL, with a bearer token minted in the admin",
    "under Connections. The reply is the result itself as JSON, with exactly the fields in that tool's",
    "Result table.",
    "",
    "```",
    "curl -H \"Authorization: Bearer $TOKEN\" -H 'content-type: application/json' \\",
    "  -d '{\"path\":\"/beers\",\"fields\":{\"name\":\"Pilsner\"}}' \\",
    "  {{api_url}}/put_item",
    "```",
    "",
    "It is plain HTTP and JSON, so any language calls it with nothing installed, and one small client",
    "covers every tool:",
    "",
    "```python",
    "import json, urllib.request",
    "",
    "def call(tool, **args):",
    "    req = urllib.request.Request(",
    "        f\"{SITE}/api/v1/{tool}\",",
    "        data=json.dumps(args).encode(),",
    "        headers={\"Authorization\": f\"Bearer {TOKEN}\", \"Content-Type\": \"application/json\"},",
    "    )",
    "    with urllib.request.urlopen(req) as r:",
    "        return json.load(r)",
    "```",
    "",
    "`GET {{api_url}}` returns the site's instructions, the access level of the token that asked, and",
    "every tool that token may call with the JSON Schema of its arguments and of its reply. That list is",
    "generated from the site, so it is never out of date.",
    "",
    "## Credentials",
    "",
    "Mint a token in the admin under Connections, and pick whether it may write or only read. A token",
    "never expires; revoking is the control, and it lands on the holder's next call because the stored",
    "record is read on every request.",
    "",
    "A read-only credential is shown only the tools marked **read** at either door. The rest are hidden",
    "from it as well as refused, so a client never builds a call it was never going to be allowed to",
    "make.",
    "",
    "## When a call fails",
    "",
    "Over MCP the failure is the reply: the message as text, with `isError: true`. Over REST it is a",
    "status and a message.",
    "",
    "| Code | Meaning |",
    "| ---- | ------- |",
    "| 200 | The tool ran. The body is its result. |",
    "| 400 | The tool refused the arguments, or the body was not a JSON object. The message says what. |",
    "| 401 | No credential, or one that has been revoked. |",
    "| 403 | A read-only credential asked for a tool that writes. |",
    "| 404 | No tool of that name. |",
    "| 405 | GET the index, POST a tool. |",
    "| 409 | A revision conflict: the `if_rev` you passed is stale. Re-read and reapply. |",
    "| 429 | Too many failed credentials from this address. `Retry-After` says when, and nothing says how close a guess came. |",
    "",
    "409 exists so a service retrying on a schedule can tell a stale revision from a dead token without",
    "reading the sentence. REST responses are never cached anywhere, because what they return varies by",
    "credential.",
    "",
    "## Bytes",
    "",
    "No tool returns the contents of a file, at either door: a reply is text in the caller's context, and",
    "a photograph spent there is one nobody can look at. Read a stored file by fetching its `/assets` URL",
    "over HTTP, with the same bearer token if it sits under a private path. Uploads go the other way as",
    "base64 through `upload_asset`, because one registry serves both services and JSON-RPC carries no",
    "bytes.",
    "",
    "## What the server tells a client",
    "",
    "This is the instruction text sent with every MCP `initialize`, and returned by `GET {{api_url}}`. It",
    "is the site teaching its own conventions, so a client on a newer deploy is taught the newer ones.",
    "",
    "{{instructions}}",
    "",
    ].join("\n"),
  },
  {
    slug: "assets",
    source: [
    "---",
    "title: Images and files",
    "order: 50",
    "---",
    "",
    "# Images and files",
    "",
    "An asset is a stored file served at its own URL. Images on a page, a PDF, a GeoJSON line, a",
    "stylesheet: anything a browser fetches and the site did not generate.",
    "",
    "## Paths and URLs",
    "",
    "Give a file a path when you upload it and it is served under `/assets` plus that path:",
    "",
    "```",
    "/kitchens/oak.jpg     →   {{site_url}}/assets/kitchens/oak.jpg",
    "```",
    "",
    "That also files it in the `/kitchens` [bundle](bundles.md), so it travels with the page when the",
    "page moves.",
    "",
    "A file uploaded without a path is stored under a hash of its bytes instead. Those URLs keep working",
    "forever and are cached forever, since the bytes behind a hash cannot change, but they sit in no",
    "bundle and cannot be moved. Prefer a path.",
    "",
    "## The site icon",
    "",
    "An asset called `favicon.ico`, `.svg`, `.png`, `.webp` or `.jpg` in the `/root` folder is the site",
    "icon, and the first of those names found wins. Uploading one is the whole of changing it: there is",
    "no setting. Until you upload one, the site serves a built-in default, so a brand new site has an",
    "icon before it has a page.",
    "",
    "## Size",
    "",
    "A file is capped at about 4 MB. That ceiling is the host's limit on a single request, not a policy,",
    "so there is no larger endpoint and no way to send a file in pieces. Something bigger has to be made",
    "smaller first.",
    "",
    "## Reading one back",
    "",
    "No tool hands back the contents of a file, at either door. A reply is text in the calling agent's",
    "context, and a three megabyte photograph spent there is one nobody can look at.",
    "",
    "To read a stored file, fetch its URL over HTTP and save it. A file under a private path answers that",
    "fetch with the same nothing everyone else gets unless the request carries an API token or the",
    "owner's own session, which is also why the admin can open a private image and a stranger cannot tell",
    "it exists.",
    "",
    ].join("\n"),
  },
  {
    slug: "bundles",
    source: [
    "---",
    "title: Path bundles",
    "order: 70",
    "---",
    "",
    "# Path bundles",
    "",
    "Everything on the site is organized by path, exactly like a folder tree. Nothing else.",
    "",
    "## The rule",
    "",
    "A path is a **bundle**. It holds every page, collection and asset at or under it.",
    "",
    "```",
    "/trip                  bundle",
    "/trip                  page",
    "/trip/items            collection, in /trip",
    "/trip/day1             page, in /trip",
    "/trip/day1/items       collection, in /trip/day1 and in /trip",
    "/trip/images/photo.jpg  asset, in /trip",
    "```",
    "",
    "Pages, collections and assets are all just things at paths. None of them owns any other. Bundles nest,",
    "so a resource is in every bundle above it, and a path is a bundle whether or not a page sits at it.",
    "",
    "Nothing is stored. The rule is computed from paths on every request.",
    "",
    "## Matching is on segments, never string prefixes",
    "",
    "This is the one place the implementation goes wrong, and the bug is silent.",
    "",
    "`\"/photos-archive/lessons\".startsWith(\"/photos\")` is true, but `photos` and `photos-archive` are",
    "different segments, so `/photos` does not hold it. Near-miss neighbours like that are common. Compare segment",
    "arrays, not strings.",
    "",
    "| Bundle | Path | Held |",
    "|---|---|---|",
    "| `/trip` | `/trip` | yes |",
    "| `/trip` | `/trip/items` | yes |",
    "| `/trip` | `/trip/day1/items` | yes |",
    "| `/trip` | `/tripwire/items` | **no** |",
    "| `/photos` | `/photos-archive/lessons` | **no** |",
    "| `/photos-archive` | `/photos-archive/lessons` | yes |",
    "",
    "In `delete_bundle` this is the difference between a wrong listing and permanent data loss.",
    "",
    "## The one exception: nothing holds the whole site",
    "",
    "`/` would hold everything, so it is not a bundle.",
    "",
    "- **Every operation that takes a bundle path refuses `/`.** Listing, deleting, copying and moving alike, and",
    "  at both ends of a copy or move. That is the entire rule. State it that way rather than naming the tools,",
    "  so it stays true as tools are added.",
    "- **A resource may still sit at `/`.** A page, collection or asset there is an ordinary resource; it is just",
    "  not reachable through a bundle. A collection at `/` keeps its `/data/index.json` address.",
    "- **What a browser gets at `/` is the site contents**, a list of every public page, generated on every request.",
    "  Nothing publishes, edits or deletes it. `/root` names it as a path, which is what closes it and opens it with a",
    "  share link, and `/root` itself redirects to `/` so it has one URL. The `/root` folder is otherwise ordinary: the",
    "  favicon and anything else filed there behaves like any other resource.",
    "- **Nothing is migrated.** A page already stored at `/` stays exactly where it is.",
    "",
    "## Organization is not a boundary",
    "",
    "A bundle says where something lives. It says nothing about who may read or write it.",
    "",
    "- Any page may fetch any collection, from any bundle. Served JSON stays public at `/data/<path>.json`.",
    "- `set_collection_refs` may point at a collection in another bundle.",
    "- No write is ever rejected, and nothing is ever moved, renamed or deleted as a side effect.",
    "",
    "## The tools that work on a bundle",
    "",
    "`list_bundle` returns everything at or under a path, with item counts, revisions, declared references,",
    "sizes and public URLs, which is how you see what one page is made of. `copy_bundle`, `move_bundle` and",
    "`delete_bundle` take the whole thing together, and do nothing until you confirm. See",
    "[copy, move and delete](transfer.md), and the [tool reference](/docs/tools) for the calls themselves.",
    "",
    "Serving is unaffected by any of it: collection `/a/b` is served at `/data/a/b.json` as a bare JSON",
    "array, wherever the collection sits.",
    "",
    ].join("\n"),
  },
  {
    slug: "collections",
    source: [
    "---",
    "title: Data collections",
    "order: 40",
    "---",
    "",
    "# Data collections",
    "",
    "A collection is an ordered list of records at a path, stored as JSON and served to anything that",
    "asks. It is how a page stops being a document and starts being a thing you maintain.",
    "",
    "## What it is",
    "",
    "Give it a path, like `/products`, and it is served at `/data/products.json` as a bare array:",
    "",
    "```json",
    "[",
    "  { \"id\": \"pils\", \"name\": \"Pilsner\", \"price\": 3.4 },",
    "  { \"id\": \"dunkel\", \"name\": \"Dunkel\", \"price\": 3.8 }",
    "]",
    "```",
    "",
    "No wrapper object, no metadata, every item carrying its own `id`, in the order you set. A page",
    "fetches that and renders it:",
    "",
    "```html",
    "<ul id=\"beers\"></ul>",
    "<script>",
    "  fetch('/data/beers.json')",
    "    .then(function (r) { return r.json(); })",
    "    .then(function (items) {",
    "      document.getElementById('beers').innerHTML =",
    "        items.map(function (i) { return '<li>' + i.name + ' — €' + i.price + '</li>'; }).join('');",
    "    });",
    "</script>",
    "```",
    "",
    "Publish that page once. Everything after it is a change to the data.",
    "",
    "`GET /data/_collections.json` lists every collection with its path, URL, item count and revision, so",
    "a page can discover what exists with no credentials at all.",
    "",
    "## Records change one at a time",
    "",
    "Adding, changing, reordering and deleting all work on a single item. Changing a price does not send",
    "the collection anywhere; it writes one field. Nested objects and arrays inside an item are stored",
    "and served exactly as given, though merging is shallow: a nested value replaces the stored one",
    "rather than being merged into it.",
    "",
    "Order is yours and it is preserved, so a page can render the array as it arrives without sorting.",
    "",
    "## Revisions",
    "",
    "Every item carries a revision number, kept outside the stored JSON so it never shows up in what the",
    "URL serves. A write passes back the revision it read, and a write built on a stale read is refused",
    "rather than quietly overwriting a newer one. It is the reason two clients editing the same site",
    "cannot silently clobber each other.",
    "",
    "## References catch typos",
    "",
    "When a field on one collection holds an id from another — a category, a section, a status, an owner",
    "— declare it. Then a value that matches no id is rejected when it is written.",
    "",
    "This is worth doing because of how the failure looks without it. The write succeeds. The JSON is",
    "valid. The page renders. The record simply stops appearing wherever that value is used to select it,",
    "and nobody finds out until they go looking for something they know should be there.",
    "",
    "Declare the constraint when the collection is new, before there are records to audit. For records",
    "written earlier, an audit finds the damage, and it reports how much it actually checked: a",
    "collection with nothing declared comes back saying nothing was checked, not that everything is fine.",
    "",
    "## It is public",
    "",
    "The served JSON is unauthenticated. A collection under a [private path](privacy.md) is served only",
    "to a browser holding a share link, and is left out of the index entirely. Anywhere else it is",
    "readable by anyone who guesses the path, exactly like a page. Put nothing in one that you would not",
    "publish.",
    "",
    ].join("\n"),
  },
  {
    slug: "getting-started",
    source: [
    "---",
    "title: Getting started",
    "order: 5",
    "---",
    "",
    "# Getting started",
    "",
    "Four steps, no checkout, no command line. If you can click a button and pick a password, you can run",
    "this site.",
    "",
    "## 1. Deploy it",
    "",
    "Press the deploy button in the [overview](/docs). Netlify asks for an account, copies the repository",
    "into it and builds the site. That takes a minute or two and happens once.",
    "",
    "You get an address ending in `netlify.app`. That is your site.",
    "",
    "## 2. Pick a password",
    "",
    "Open it. A new site says it is ready to set up and offers one link, **Set up this site**.",
    "",
    "Pick a password and you are the owner. That is the whole of setup: there are no accounts to create",
    "and nobody else to invite, because a site has one owner and everything else is either published or",
    "closed.",
    "",
    "Your site now serves a home page listing everything you publish. It has nothing on it yet.",
    "",
    "## 3. Connect Claude",
    "",
    "In the admin, open **Connections**. It shows one URL:",
    "",
    "```",
    "{{mcp_url}}",
    "```",
    "",
    "In Claude, add that as a custom connector. Claude sends you back to your own site to sign in with",
    "the password you just picked, and asks you to approve the connection. Approve it.",
    "",
    "Claude can now read and write your site. Nothing else can: the connection is to your site, from your",
    "Claude account.",
    "",
    "A script, a cron job or an agent connects differently, with a token you mint on the same screen.",
    "See [connecting a client](api.md).",
    "",
    "## 4. Ask for a page",
    "",
    "Then talk to Claude:",
    "",
    "> Publish a page at /about that says who I am. I'm a cabinetmaker in Ashford, I've been doing it for",
    "> twenty years, and I mostly build kitchens.",
    "",
    "Claude writes it and publishes it. It is live at `{{site_url}}/about` immediately: nothing is built,",
    "no deploy runs, and there is nothing to wait for.",
    "",
    "Open your home page and the new page is listed on it.",
    "",
    "## Where to go next",
    "",
    "- [Working with Claude](with-claude.md) — what to ask for, and what it is good at",
    "- [Pages](pages.md) — markdown, HTML, and how a page's address is decided",
    "- [Data collections](collections.md) — the thing to use before a page grows a list",
    "",
    ].join("\n"),
  },
  {
    slug: "maps",
    source: [
    "---",
    "title: Maps",
    "order: 90",
    "---",
    "",
    "# Maps",
    "",
    "Two tools, `geocode` and `route`, and no map code anywhere in the site.",
    "",
    "## What the site does and does not do",
    "",
    "A map is a page. The site stores the data behind one and serves it, exactly as it does for anything",
    "else: the stops are a collection, the route geometry is an asset, the map is a page that fetches",
    "both and draws them with a library from a CDN. Nothing in this repo knows what a tile is.",
    "",
    "What the site does own is the two things a client cannot do for itself without a shell: turning a",
    "place name into coordinates, and turning coordinates into a line that follows real ways. Both run",
    "once, while a page is being written, and their answers are stored.",
    "",
    "```",
    "authoring (once)          stored (forever)              page load (every visit)",
    "─────────────────         ────────────────              ──────────────────────",
    "geocode  →  lat/lon   →   collection item          →    GET /data/<path>.json",
    "route    →  geometry  →   asset, GeoJSON           →    GET /assets/<path>.geojson",
    "                                                        + tiles + library, from a CDN",
    "```",
    "",
    "## The rule that keeps this from becoming an integration platform",
    "",
    "> **The site may do authoring-time work whose output it stores. It may never fetch at request time.**",
    "",
    "Geocoding and routing qualify: each produces durable content. A weather feed, a live price or a",
    "transit departure does not, and putting one behind a tool would place a provider in front of every",
    "visitor and make a response that cannot be cached at the edge. That is the line, and it is the same",
    "one that already separates a collection from a page that renders one.",
    "",
    "These are the first outbound calls the site makes. Before them, the function called nothing.",
    "",
    "## Result shapes are provider-neutral on purpose",
    "",
    "A handler's result is published API, so a vendor identifier in one would marry the API to that",
    "vendor for the life of the API. Every adapter maps its provider's answer onto the intersection of",
    "what all of them can produce, and never passes anything through:",
    "",
    "- **No vendor ids.** No `place_id`, no `mapbox_id`, no provider-specific encoding.",
    "- **No vendor score scales.** `confidence` is comparable between candidates in one response and",
    "  nowhere else, and says so.",
    "- **No formatted labels.** `name` and `context` are components. A caller composes what it displays.",
    "- **No styling.** There is an established convention for putting `stroke` and `stroke-width` into",
    "  GeoJSON properties and it is the wrong place for it. Appearance belongs to the page, and a stored",
    "  line outlives every design it is ever drawn in.",
    "- **SI units.** `distance_m`, `duration_s`, `ascent_m`. Kilometres and minutes are presentation.",
    "",
    "`null` where a provider does not report something, never zero: no answer and no climb are different",
    "facts, and a cyclist reading the second as the first is being misled.",
    "",
    "## geocode returns candidates, never an answer",
    "",
    "A geocoder is a guess, and the caller is the only thing that can judge it. Returning one row invites",
    "a service to take it, and a wrong Springfield is silent on every axis: the write succeeds, the JSON",
    "validates, the page renders, and the pin is simply in the wrong place.",
    "",
    "Two failures are worth naming because both look like success:",
    "",
    "- **Nothing matched** is not a bad match. Over-qualifying is the usual cause: adding a",
    "  district, a region and a country to a town name can return nothing where the town alone is found.",
    "- **The wrong granularity.** A town is an area and a station is a point. Asking for `Zürich` and",
    "  asking for `Bahnhof Zürich` give answers 2.5 km apart, and both are correct.",
    "",
    "Coordinates are stored as separate numeric `lat` and `lon` fields, never a two-element array.",
    "GeoJSON orders them `[lon, lat]` and most map libraries take `[lat, lon]`, so a transposed pair",
    "validates, renders and is wrong. `route` refuses a bare pair outright rather than guessing at it.",
    "",
    "## route writes the asset and returns a summary",
    "",
    "The line is never returned. A 126 km road route is 3330 points and 75 KB; handing that to a caller",
    "so the caller can hand it back spends the whole thing twice and asks every client to reimplement the",
    "same simplification. What comes back is distance, duration, ascent, point count and the asset url,",
    "which is what a caller actually reads.",
    "",
    "**Simplification is off by default and takes metres.** How much detail a line needs is a question",
    "about the zoom it will be drawn at, and that is the page's decision, not storage's. Points that",
    "survive are returned exactly as the router sent them, elevation included: thinning a line must never",
    "also edit the points it keeps.",
    "",
    "## Bike routes: choosing, then checking",
    "",
    "Two different jobs, and a bike page needs both.",
    "",
    "**Choosing** is `prefer`: `safety`, `balanced` or `speed`, cycling only. A real trade, measured on one",
    "67 km ride:",
    "",
    "| prefer | distance | main roads | on a signed cycle route |",
    "| --- | --- | --- | --- |",
    "| `safety` | 68.7 km | 2.7 km | 93% |",
    "| `balanced` | 67.1 km | 4.5 km | 89% |",
    "| `speed` | 63.8 km | 48.4 km | 10% |",
    "",
    "Safety buys that with unpaved: it adds around 2 km of track and path. Whether that is a good trade is",
    "the rider's call, which is the argument for reporting the mix rather than scoring it. Asking for a",
    "`prefer` on a walking or driving route is refused rather than ignored, because a caller who asked for",
    "a safer line and silently got the ordinary one believes something untrue about their route.",
    "",
    "**Checking** is `ways` in the reply: metres by surface, metres by highway type, metres on a signed",
    "cycle route, and `warnings` for explicit prohibitions. Only unambiguous ones — `bicycle=no`,",
    "`bicycle=dismount`, `access=private`, `access=no`. \"Busy road\" is an opinion; `bicycle=no` is a fact",
    "somebody went and wrote down. That ride has 96 m of it, at both ends, which no profile avoids because",
    "it is the way in and out of Springfield's old town.",
    "",
    "**`analyzed_m` is the honesty field.** It is how much of the route carried tags at all, and it is `0`",
    "when the router reports none, which is the `check_refs` rule again: a summary",
    "that checked nothing must not read like a summary that passed. Untagged ground is counted under",
    "`untagged` in the breakdowns for the same reason. OSM coverage varies widely by region, near",
    "total in some places and thin in others, and a route that is 40% untagged must not look like a",
    "route that is 40% asphalt.",
    "",
    "**None of it is a safety score**, and nothing here will add one. Safe depends on whether it is you or",
    "a seven-year-old, a score cannot survive a provider change, and the moment one exists people stop",
    "reading the breakdown.",
    "",
    "The stored asset carries a per-way `segments` table keyed to coordinate indices, so a page can colour",
    "the line by surface and point at the stretch it warns about. Simplification remaps those indices,",
    "because thinning the line must never leave the table pointing at the wrong places while still looking",
    "valid.",
    "",
    "## Providers",
    "",
    "| profile | keyless | with `ORS_API_KEY` |",
    "| --- | --- | --- |",
    "| cycling | BRouter, `safety` / `trekking` / `fastbike` by `prefer` | openrouteservice, `cycling-regular` |",
    "| walking | BRouter, `hiking-beta` | openrouteservice, `foot-walking` |",
    "| driving | OSRM | openrouteservice, `driving-car` |",
    "| geocoding | Nominatim | openrouteservice (Pelias) |",
    "",
    "**Cycling and walking must never go to the public OSRM server.** It is a car-only deployment that",
    "accepts any profile in its path and answers identically either way: `driving`, `bike` and `foot`",
    "return the same distance and duration for the same pair. A walking route that is silently a motorway",
    "is exactly the failure this codebase refuses everywhere else.",
    "",
    "BRouter answers in GeoJSON already, carries elevation as a third ordinate, and reports a *filtered*",
    "ascent rather than the sum of every wobble in the terrain data, which is the number a cyclist wants.",
    "It returns one line and no per-stop breakdown, so `legs` comes back empty; OSRM and openrouteservice",
    "fill it. An empty `legs` means the router does not break the line down, not that the route has one",
    "leg.",
    "",
    "All of these are fair-use services. `ORS_API_KEY` buys an SLA, and today it costs two things: there is",
    "no equivalent of BRouter's `safety` profile, so a non-balanced `prefer` is refused rather than",
    "approximated, and openrouteservice reports surface through a different encoding that nothing here has",
    "been able to verify against a real key, so `analyzed_m` comes back `0`. Both are stated by the",
    "response rather than papered over. Wiring `extra_info` up is the obvious next job.",
    "",
    "## Drawing the map",
    "",
    "The site stores the data and does not draw the map. A client is told to keep the stops in a",
    "collection, fetch the asset for the line, route once rather than on every visit, and carry the",
    "attribution string, which is a licence condition rather than a courtesy.",
    "",
    "Renderer and tiles are page decisions the repo has no opinion about. Leaflet is small and takes",
    "raster tiles; MapLibre GL is larger, takes vector tiles and can be restyled in the browser. The",
    "stored line is plain GeoJSON and is tied to neither, so swapping one for the other touches no data.",
    "",
    ].join("\n"),
  },
  {
    slug: "pages",
    source: [
    "---",
    "title: Pages",
    "order: 30",
    "---",
    "",
    "# Pages",
    "",
    "A page is a path and a body. The body is markdown or a whole HTML document, it is stored exactly as",
    "written, and the next request serves it. Nothing is compiled, and there is no template to fill in.",
    "",
    "## Markdown is themed, HTML is verbatim",
    "",
    "Write markdown and the site wraps it in its own theme: the site title and description at the top,",
    "the content below, a light and a dark scheme, and nothing else. There is no navigation bar, because",
    "a site's links are its owner's business: a page that wants to link elsewhere says so in its own",
    "words.",
    "",
    "Write a full HTML document, starting `<!doctype html>` or `<html>`, and it is served byte for byte.",
    "Your own CSS, your own scripts, a library from a CDN, a map, a canvas, whatever you like. The site",
    "adds nothing to it and takes nothing out, which is also why it cannot give it a favicon tag or a",
    "theme toggle: a verbatim document is verbatim.",
    "",
    "Which one you get is detected from the content unless you say. Ask Claude for \"a plain page\" and you",
    "will get markdown; ask for something designed and you will get HTML.",
    "",
    "## The address",
    "",
    "Paths are lowercased, and `.md`, `.markdown`, `.html` and `.htm` are stripped, so `/About.HTML` and",
    "`/about` are the same page. A trailing `index` is dropped: `/docs/index` is `/docs`. Use lowercase",
    "letters, numbers, dashes and slashes.",
    "",
    "A page's title is the first heading in its body, or the `<title>` of an HTML document, unless one is",
    "given. The title is what the home page lists it as.",
    "",
    "## The home page is not a page",
    "",
    "`/` is the contents of the site: a list of every public page, generated on every request. Nobody",
    "writes it, nobody has to keep it current, and it cannot be published to, edited or deleted. Publish",
    "anywhere else and it appears there.",
    "",
    "It is still a path, and its name is `/root`. That matters in three places: it is what you make",
    "private to close the site to the public, it is where a share link for the whole site points, and it",
    "is where the [favicon](assets.md) lives. `/root` itself redirects to `/`, so the contents has one",
    "address.",
    "",
    "A private page is left out of the list for everyone, link holders included, because a page that",
    "varied by who was asking could not be cached, and the next visitor would get somebody else's copy.",
    "",
    "## Editing",
    "",
    "Ask for a change and Claude replaces the part it is changing, leaving every other byte alone. That",
    "is cheaper than rewriting the page, and safer: a hand-written HTML page survives an edit to one",
    "paragraph.",
    "",
    "The admin has an editor for the times it is faster to fix a word yourself. It shows the page's path",
    "and offers a link to move it, never a box to retype it in: retyping a path writes a new page and",
    "strands everything filed under the old one. See [copy, move and delete](transfer.md).",
    "",
    "## A page that lists things should fetch them",
    "",
    "If a page holds a list you will add to — products, posts, events, opening times — the list belongs",
    "in a [collection](collections.md) and the page should fetch it. The page is then written once and",
    "the list changes without it. This is the one piece of advice on this whole site that saves real",
    "work, and it is easy to skip on the day the list has three things in it.",
    "",
    ].join("\n"),
  },
  {
    slug: "privacy",
    source: [
    "---",
    "title: Private paths",
    "order: 60",
    "---",
    "",
    "# Private paths",
    "",
    "A path can be closed to the public and opened with a link. It is the right tool for a draft, a",
    "family album or a client preview, and the wrong tool for anything whose exposure would actually",
    "hurt. The difference matters, so this page says plainly what it is.",
    "",
    "## What closing a path does",
    "",
    "Making `/trip` private closes `/trip`, every page under it, every collection served under",
    "`/data/trip/` and every asset under `/assets/trip/`. One path, one rule, the same folder rule as a",
    "[bundle](bundles.md).",
    "",
    "To anyone without a link, all of it answers exactly as if nothing had ever been published there:",
    "the same document, the same status, the same headers, byte for byte. A private path does not",
    "announce that it exists, which is the whole point. It also drops out of the home page listing, for",
    "everybody, link holders included.",
    "",
    "Privacy does not nest — a path inside a private path cannot be a second scope — and `/` cannot be",
    "private, because that is the entire site rather than a path within it. To close a whole site, make",
    "`/root` private.",
    "",
    "## The link",
    "",
    "A share link carries its secret after the `#`:",
    "",
    "```",
    "{{site_url}}/trip#uNqL7v…",
    "```",
    "",
    "Browsers never send the fragment to a server. It reaches no access log, no proxy, no `Referer`",
    "header, and a chat or mail app that previews links by fetching them gets the same nothing a stranger",
    "gets. That is what makes the link safe to send through a channel you do not control.",
    "",
    "It costs one thing: the token only ever arrives in a browser, so opening a link needs JavaScript on.",
    "The script that reads the fragment rides on the response a stranger already gets, which is why the",
    "closed page and a missing page are the same document.",
    "",
    "Pass a link on exactly as given. Trimmed at the `#`, it opens nothing. It is shown once, because",
    "only a hash of it is stored.",
    "",
    "## Links are per recipient",
    "",
    "Mint one link per person and label it with who it is for. Revoking then kills one person's access",
    "and leaves everybody else working.",
    "",
    "Revocation lands on that holder's next request, not whenever their browser would have forgotten",
    "something, because every request checks the link against the stored list. Revoking the last link",
    "leaves the path closed to everyone rather than quietly republishing it.",
    "",
    "## What it is not",
    "",
    "Anyone holding the link is in. There is no account, no identity and no audit trail beyond when a",
    "link was last used. Treat it as \"unlisted, and hard to guess\", not as a login.",
    "",
    "Making a path public again revokes every link on it, because those links exist only to open",
    "something closed.",
    "",
    ].join("\n"),
  },
  {
    slug: "tools",
    source: [
    "---",
    "title: Tool reference",
    "order: 25",
    "---",
    "",
    "# Tool reference",
    "",
    "One API, two services in front of it. Every tool here is the same tool whichever way it is called:",
    "the same name, the same arguments, the same result. Nothing is offered over one and withheld from",
    "the other, and the entry below is written once for both. The tabs on each call show the only part",
    "that differs, which is the envelope it travels in.",
    "",
    "**MCP** is JSON-RPC over Streamable HTTP, for a chat client that can sign a person in. The reply is",
    "text: the result rendered into a sentence for a reader. A tool that refuses answers with that same",
    "text and `isError: true`, so a failure arrives as a successful JSON-RPC response and there is no",
    "status code to read.",
    "",
    "**REST** is one POST per call, for a script, a cron job or an agent with no browser. The reply is",
    "the result itself, as JSON, with exactly the fields in its Result table. A failure is an HTTP status",
    "and a message.",
    "",
    "Signing in, tokens, status codes and the rest of what separates the two are in",
    "[connecting a client](api.md).",
    "",
    "The credential decides what may be called, not the door it came through. A read-only token is shown",
    "only the tools marked **read**; the rest are hidden from it as well as refused, so a client never",
    "builds a call it was never going to be allowed to make.",
    "",
    "The example on each call carries its required arguments only, with a placeholder for each value.",
    "**Arguments** lists everything it takes, required and optional. **Result** is what comes back: a",
    "field marked *always* is one a caller can count on, and *sometimes* means it depends, which the",
    "note on that row explains.",
    "",
    ].join("\n"),
  },
  {
    slug: "transfer",
    source: [
    "---",
    "title: Copy, move and delete",
    "order: 80",
    "---",
    "",
    "# Copy, move and delete",
    "",
    "Twelve tools, one engine, one reply. Reorganizing a site runs on the server, so nothing is read out",
    "and written back, and nothing is lost on the way.",
    "",
    "## Why it runs on the server",
    "",
    "Reorganizing a site must never mean reading records out through a client and writing them back. That round",
    "trip is slow, and it is lossy in a way a server-side operation is not: ids, array order, revs and declared",
    "refs survive only if the client reproduces them exactly, and every string is a chance to mistype an umlaut",
    "or drop a nested field.",
    "",
    "Moving six collections by hand costs roughly 500 tool calls and passes every stored",
    "byte through a language model twice.",
    "",
    "## Three verbs, four levels",
    "",
    "Twelve tools, one engine, one reply shape.",
    "",
    "| | page | collection | asset | bundle |",
    "|---|---|---|---|---|",
    "| copy | `copy_page` | `copy_collection` | `copy_asset` | `copy_bundle` |",
    "| move | `move_page` | `move_collection` | `move_asset` | `move_bundle` |",
    "| delete | `delete_page` | `delete_collection` | `delete_asset` | `delete_bundle` |",
    "",
    "- **A delete is a transfer with no target.** That is why all twelve share arguments and reply.",
    "- **Copy and move take `from` and `to`. Delete takes `path`.**",
    "- **`overwrite` on copy and move**, default false. **`confirm` on the bundle verbs.** **`if_rev` on the",
    "  collection verbs.**",
    "- **The level says what travels.** `move_collection` leaves the page that renders it behind;",
    "  `move_page` leaves its data behind; `move_bundle` takes the page, its collections and its assets together.",
    "",
    "Item-level operations stay out of scope: `put_item` and `delete_item` already change one item at a time.",
    "",
    "## What is preserved",
    "",
    "- **Item ids and array order, exactly.** Order is the collection order and pages rely on it.",
    "- **Every field value byte for byte**, including nested objects and arrays of objects.",
    "- **Item revs on a move.** A copy is a new collection and starts at fresh revs; both are stated in the reply.",
    "- **Bytes on an asset copy or move**, with the filename and content type intact.",
    "- **Page bodies verbatim.** A copied page keeps the URLs written into it, so it still fetches the original's",
    "  data until someone edits it. See section 6.",
    "",
    "Replacing an occupied target always bumps the rev past what that target held, so no rev a client is holding",
    "is ever reused for different content.",
    "",
    "## Declared references",
    "",
    "- **Carried to the target.** A copy or move never silently drops a declaration.",
    "- **Rewritten inside the operation.** A ref pointing at a collection moving in the same call follows it, so",
    "  `move_bundle('/trip', '/gf')` leaves `/gf/items` declaring `group` against `/gf/filters`.",
    "- **Left alone outside it.** Cross-bundle references are legitimate, so they are never rewritten.",
    "- **Reported when broken.** A move takes the source path away just as a delete does, so refs from outside",
    "  the operation are listed in `breaks` rather than being refused or silently repointed.",
    "",
    "## Collisions, and what happens when one fails",
    "",
    "- **Refuses an occupied target**, naming what is there, unless `overwrite: true`.",
    "- **Refuses a no-op** where `from` and `to` normalize to the same path.",
    "- **Refuses a bundle target nested in its own source**, which would consume itself. A single-resource move",
    "  to a nested path is fine and allowed, because nothing recurses.",
    "- **Refuses `/` at either end of a bundle verb.** `/` is not a bundle; see [bundles](bundles.md) for why.",
    "  Refuses `/_collections` as a bundle path and as a collection path.",
    "- **Normalizes both paths by kind.** Assets use `normalizeAssetPath` so a filename survives; pages and",
    "  collections use `normalizePath`, and a trailing `.json` on a collection is ignored.",
    "- **Atomic.** Every source is read and every target staged before a byte is written; each write carries its",
    "  own undo and a failure unwinds in reverse. A partially populated target is never observable.",
    "- **A bundle verb always asks twice.** Without `confirm: true` it changes nothing and returns the inventory",
    "  it would write or remove.",
    "",
    "## Page content is never rewritten",
    "",
    "Pages hardcode the URLs they fetch. There is no reliable way to tell which strings in arbitrary HTML are a",
    "URL, so no operation edits a page.",
    "",
    "Instead every move and delete reports `pages_to_update`: each page path with the matching lines and line",
    "numbers. The scan matches a collection's `/data` URL and its parent prefix, which is what finds a",
    "`const BASE = \"/data/trip/\"`, an asset's `/assets` URL the same way, and a page path on segment boundaries",
    "so a link to `/trip` is not reported for `/tripwire`.",
    "",
    "A URL a page assembles from pieces cannot be found at all. That is why the reply reports lines to read",
    "rather than promising a clean result, and why a client that cannot break a page even briefly should copy,",
    "repoint the page, confirm it renders, then delete the source.",
    "",
    "## The reply",
    "",
    "Every tool returns the same envelope: `operation`, `scope`, `from`, `to`, `applied`, `resources`, `breaks`,",
    "`pages_to_update`, `notes`, and `rest_of_bundle` on a page verb. Each resource carries its kind, both paths,",
    "the target URL and whether it replaced something, plus item count, rev and refs for a collection and size for",
    "an asset. A page may never land on `/root`: the site root is generated, so a page verb naming it and a bundle verb",
    "that would carry one there are both refused before anything is written.",
    "",
    "That is enough to verify the result without a follow-up call.",
    "",
    "## What it does not do",
    "",
    "It never edits a page, under any flag. It does not move or merge individual items between",
    "collections, since those already change one at a time, and it does not rename or reshape fields on",
    "the way past. Nothing here runs on a schedule: a transfer happens because somebody asked for one.",
    "",
    ].join("\n"),
  },
  {
    slug: "with-claude",
    source: [
    "---",
    "title: Working with Claude",
    "order: 10",
    "---",
    "",
    "# Working with Claude",
    "",
    "The site has no page builder, no templates and no drag and drop. You describe what you want and",
    "Claude writes it, publishes it, and changes it when you ask again. This page is about asking well.",
    "",
    "Everything below assumes the connector is set up. If it is not, start at",
    "[getting started](getting-started.md).",
    "",
    "## Say what the page is for, not what to type",
    "",
    "Claude writes better from a purpose than from dictation.",
    "",
    "> Make a page for my kitchen work. Six or seven photos, a short paragraph each, and my phone number",
    "> at the bottom. Keep it plain and readable.",
    "",
    "You will get a whole page. Then correct it in place:",
    "",
    "> The intro is too long, cut it to two sentences. And move the phone number under the heading.",
    "",
    "Claude edits the part it is changing rather than rewriting the page, so the rest of it stays exactly",
    "as it was, including anything you had it write earlier.",
    "",
    "## Ask it to go and find out",
    "",
    "Claude can research first and publish second, and the second half is one instruction:",
    "",
    "> Find the opening times and ticket prices for the three museums in Ashford, check them against the",
    "> official sites, and publish a page at /ashford/museums with a table.",
    "",
    "Ask it to say where the facts came from. It will put the sources on the page if you ask, and leave",
    "them off if you do not.",
    "",
    "## When something repeats, ask for data",
    "",
    "The single most useful habit: the moment a page holds a *list* of anything you will add to later,",
    "say so.",
    "",
    "> Keep the museums as data rather than typing them into the page.",
    "",
    "Claude puts each one in a [collection](collections.md) and writes a page that fetches it. Then",
    "adding the fourth museum is one sentence, and the page itself never changes:",
    "",
    "> Add the Natural History Museum to the museums, opens at 9, adults €5.",
    "",
    "Without that, changing an opening time means rewriting the page. It is the difference between a site",
    "you keep and a site you rebuild.",
    "",
    "## Pictures and files",
    "",
    "Claude can upload an image it has: one you attached to the chat, one it made, one it fetched. Ask",
    "for it to be filed under the page that uses it.",
    "",
    "> Put these three photos under /kitchens and use them on that page.",
    "",
    "Files are capped at about 4 MB each, which is the host's limit rather than a setting, so a large",
    "photo has to be made smaller before it goes up. Claude cannot hand you a file back down the chat: to",
    "see one, open its URL. See [assets](assets.md).",
    "",
    "## Moving things later",
    "",
    "Paths work like folders, so a section of your site is a path and everything under it. When you",
    "outgrow a name, say so:",
    "",
    "> Rename /kitchens to /work, everything under it.",
    "",
    "That moves the page, the photos and the data in one go, on the server, with nothing passing through",
    "the conversation. Claude will tell you what it could not fix: any page that still links to the old",
    "address. See [copy, move and delete](transfer.md).",
    "",
    "## Showing someone a draft",
    "",
    "> Make /work private and give me a link for my sister.",
    "",
    "A private path disappears for everyone else, and the link opens it. It is a link, not a login:",
    "anyone who has it is in. Good for a draft or a family album, wrong for anything whose exposure would",
    "actually hurt. See [private paths](privacy.md).",
    "",
    "## Maps",
    "",
    "> Put a map on /tour with the five stops, and route between them by bike.",
    "",
    "The stops become data you can edit later, the route is worked out once and stored, and the page",
    "draws both. Ask what the route is made of before you ride it: Claude can tell you how much of it is",
    "on main roads. See [maps](maps.md).",
    "",
    "## Two things worth knowing",
    "",
    "**It is live.** There is no draft mode and no publish button. When Claude says it published",
    "something, it is on the internet at that address. Ask for a private path first if that matters.",
    "",
    "**It never touches a repository.** If Claude starts talking about committing, pushing or waiting for",
    "a deploy, it has the wrong idea of what this site is: ask it to read the site's instructions again.",
    "Your content lives in the site's own storage, never in the code.",
    "",
    "## Checking its work",
    "",
    "- Your home page lists every public page. Open it.",
    "- The admin lists pages, assets and collections, and has an editor for when you would rather change",
    "  one word yourself than describe it.",
    "- Claude gives you the URL of anything it writes. Open that too. It is the fastest way to catch a",
    "  page that reads well in a chat and badly in a browser.",
    "",
    ].join("\n"),
  },
];
